version: "3.8"
services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 bot/main.py
    restart: always
    env_file:
      - .env
    networks:
      - app-network

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 scheduler/main.py
    restart: always
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network



networks:
  app-network:
    driver: bridge